import type {
  BanterTemplate,
  DilmondoStore,
  HomepageAnnouncement,
  LeagueSettings,
  Member,
} from "@/lib/types";

export const DEFAULT_LEAGUE_ID = Number(process.env.FPL_LEAGUE_ID ?? 403186);
export const DEFAULT_LEAGUE_NAME = "Dilmondo 7th 🏆";

export function createSeedMembers(now = new Date().toISOString()): Member[] {
  return [
    {
      id: "mohamed-adil-taha",
      fplManagerId: null,
      fplTeamName: "Abu kalam ☆°",
      fplManagerName: "Mohammed Adil",
      standingReference: 1,
      displayNameAr: "محمد عادل حسن طه",
      shortName: "محمد عادل",
      nickname: "معالي الأسطورة",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#f5c542",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "mohamed-abdelkader",
      fplManagerId: null,
      fplTeamName: "Arkab Alzalat",
      fplManagerName: "Mohamed Adil J",
      standingReference: 2,
      displayNameAr: "محمد عادل عبد القادر",
      shortName: "محمد عبد القادر",
      nickname: "Arkab Alzalat",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#38bdf8",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "gamal-abdelrahman",
      fplManagerId: null,
      fplTeamName: "Gamal",
      fplManagerName: "Gamalelden A M Ahmed",
      standingReference: 3,
      displayNameAr: "جمال عبد الرحمن",
      shortName: "جمال",
      nickname: "Gamal",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#22c55e",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "moyad-i",
      fplManagerId: null,
      fplTeamName: "Fulcurm FC",
      fplManagerName: "Moyad I",
      standingReference: 4,
      displayNameAr: "مؤيد عادل",
      shortName: "مؤيد",
      nickname: "Fulcurm",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#a78bfa",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "mohamed-saif",
      fplManagerId: null,
      fplTeamName: "HA MA DA FC",
      fplManagerName: "Hamada Saif",
      standingReference: 5,
      displayNameAr: "محمد سيف",
      shortName: "محمد سيف",
      nickname: "HA MA DA FC",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#fb7185",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "maaz-adil",
      fplManagerId: null,
      fplTeamName: "Jghim",
      fplManagerName: "Maaz Adil",
      standingReference: 6,
      displayNameAr: "معاذ عادل",
      shortName: "معاذ",
      nickname: "Jghim",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#2dd4bf",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "abdelrahman-saifaldeen",
      fplManagerId: null,
      fplTeamName: "AlsAmAk",
      fplManagerName: "Abdo Saifaldeen",
      standingReference: 7,
      displayNameAr: "عبد الرحمن سيف الدين",
      shortName: "عبد الرحمن",
      nickname: "AlsAmAk",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#60a5fa",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "moyad-adil-restored",
      fplManagerId: null,
      fplTeamName: "Restored",
      fplManagerName: "Moyad Adil",
      standingReference: 8,
      displayNameAr: "مؤيد عادل",
      shortName: "مؤيد عادل الثاني",
      nickname: "Restored",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#f97316",
      banterLevel: "normal",
      active: true,
      status: "active",
      notes: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "mohamed-kamal",
      fplManagerId: null,
      fplTeamName: null,
      fplManagerName: null,
      standingReference: null,
      displayNameAr: "محمد كمال",
      shortName: "محمد كمال",
      nickname: "المنسحب التاريخي",
      profileImageUrl: null,
      avatarUrl: null,
      customColor: "#94a3b8",
      banterLevel: "light",
      active: false,
      status: "withdrawn",
      notes: "يظهر في قسم المنسحبين فقط، ولا يظهر في الترتيب الحي إلا إذا ربطه المشرف بفريق FPL صالح.",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createDefaultBanterTemplates(): BanterTemplate[] {
  return [
    {
      id: "gw-low-score",
      name: "جولة للنسيان",
      triggerKey: "gw_points_below",
      conditionConfig: { value: 40 },
      textAr: "جولة للنسيان... الأفضل عدم فتح القروب اليوم.",
      banterLevel: "normal",
      active: true,
    },
    {
      id: "gw-high-score",
      name: "تصفيق الجولة",
      triggerKey: "gw_points_above",
      conditionConfig: { value: 70 },
      textAr: "أداء محترم جداً... جولة تستحق التصفيق.",
      banterLevel: "light",
      active: true,
    },
    {
      id: "last-place",
      name: "القاع التاريخي",
      triggerKey: "last_place",
      conditionConfig: {},
      textAr: "القاع ليس مكاناً... القاع أسلوب حياة.",
      banterLevel: "normal",
      active: true,
    },
    {
      id: "captain-low",
      name: "تحقيق الكابتن",
      triggerKey: "captain_points_below",
      conditionConfig: { value: 4 },
      textAr: "قرار الكابتن يحتاج لجنة تحقيق.",
      banterLevel: "normal",
      active: true,
    },
  ];
}

export function createDefaultStore(): DilmondoStore {
  const now = new Date().toISOString();
  const leagueSettings: LeagueSettings = {
    id: "primary",
    leagueId: DEFAULT_LEAGUE_ID,
    leagueName: DEFAULT_LEAGUE_NAME,
    seasonName: "2025/26",
    seasonStatus: "active",
    lastSyncAt: null,
    syncStatus: "idle",
    syncError: null,
  };

  const announcement: HomepageAnnouncement = {
    id: "welcome",
    title: "المسرح مفتوح",
    body: "الصدارة لا تكفي... المهم أن تنجو من تعليقات العائلة.",
    active: true,
    createdAt: now,
  };

  return {
    leagueSettings,
    members: createSeedMembers(now),
    standingsSnapshots: [],
    managerGameweekSnapshots: [],
    banterTemplates: createDefaultBanterTemplates(),
    hallOfFame: [],
    homepageAnnouncements: [announcement],
  };
}
